Actualización
1-DAM-IES-Macia-Abela-2023-24/Guia-GIT pull request #19
Opened 2023-12-17 11:06 UTC by CristianRedondoRuz

Actualizo pagina gitBranch, ha quedado bastante bien.

2023-12-18 14:33 UTC, Sacha1083 approved these changes

2023-12-19 18:31 UTC, AndresProfIEsMaciaAbela requested changes
Cambia el title

2023-12-19 18:32 UTC, AndresProfIEsMaciaAbela requested changes
quita los desktop.ini

2023-12-19 18:33 UTC, AndresProfIEsMaciaAbela requested changes
Añade el link a tu página en index.html

2023-12-23 12:29 UTC, CristianRedondoRuz commented
actualizo git branch e index.

2023-12-23 12:38 UTC, closed without merging